@BASE_URL=http://localhost:3000
@USER_ID=6143ea36-01b5-404c-9e8d-39a50531a219
@USER_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDNlYTM2LTAxYjUtNDA0Yy05ZThkLTM5YTUwNTMxYTIxOSIsImVtYWlsIjoidGVzdDJAZG9lLmNvbSIsInVzZXJuYW1lIjoidGVzdF9kb2UyIiwiZnVsbE5hbWUiOiJUZXN0IERvZSIsImNyZWF0ZWRBdCI6IjIwMjUtMDMtMTBUMjE6MTY6NDEuMjQ5WiIsInVwZGF0ZWRBdCI6IjIwMjUtMDMtMTBUMjE6MTY6NDEuMjQ5WiIsImlhdCI6MTc0MTY0MTQxMSwiZXhwIjoxNzQxNjQyMDExfQ.GpfDr-C7L26-nS_g5cy1Owpql83t2ZiP4QTpjgLgdU4
@POST_ID=0c63bb7f-7e49-4674-a58c-a2de42199bf8


### Login

POST {{BASE_URL}}/sign-in
Content-Type: application/json

{
    "username": "test_doe",
    "password": "password"
}

### Create a new user

POST {{BASE_URL}}/users
Content-Type: application/json

{
    "email": "test@doe.com",
    "username": "test_doe",
    "fullName": "Test Doe",
    "password": "password"
}

### 2. Get all posts (without authentication)

GET {{BASE_URL}}/posts
Content-Type: application/json

### 3. Get all posts

GET {{BASE_URL}}/posts
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

### 4. Create a new post

POST {{BASE_URL}}/posts
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

{
    "authorId": "{{USER_ID}}",
    "title": "Post 1",
    "content": "Content 1"
}

### 5. Get a post by id

GET {{BASE_URL}}/posts/{{POST_ID}}
Content-Type: application/json

### 6. Get posts by query

GET {{BASE_URL}}/posts/search?query=pos
Content-Type: application/json

### 7. Update a post

PUT {{BASE_URL}}/posts/{{POST_ID}}
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

{
    "title": "Post 1 Updated",
    "content": "Content 1 Updated"
}

### 8. Delete a post

DELETE {{BASE_URL}}/posts/{{POST_ID}}
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}